name: versioning
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  bump-patch:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-patch')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BYPASS_PUSH }}
      - run: git config user.email "$mailto:GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version patch
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.BYPASS_PUSH }}@github.com/$GITHUB_REPOSITORY.git"
  bump-minor:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-minor')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BYPASS_PUSH }}
      - run: git config user.email "$mailto:GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version minor
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.BYPASS_PUSH }}@github.com/$GITHUB_REPOSITORY.git"
  bump-major:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-major')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BYPASS_PUSH }}
      - run: git config user.email "$mailto:GITHUB_ACTOR@users.noreply.github.com"
      - run: git config user.name "$GITHUB_ACTOR"
      - run: npm version major
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.BYPASS_PUSH }}@github.com/$GITHUB_REPOSITORY.git"
