name: versioning
on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  bump-patch:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-patch')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "github-actions[bot]"
      - run: git config user.name "github-actions[bot]@users.noreply.github.com"
      - run: npm version patch
      - run: git push
  bump-minor:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-minor')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "github-actions[bot]"
      - run: git config user.name "github-actions[bot]@users.noreply.github.com"
      - run: npm version minor
      - run: git push
  bump-major:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump-major')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config user.email "github-actions[bot]"
      - run: git config user.name "github-actions[bot]@users.noreply.github.com"
      - run: npm version major
      - run: git push
